[package]
name = "transformers-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.6.1"
tokenizers = "0.11.0"
anyhow = "1.0.45"