name: "pipeline"
backend: "python"

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "PREDICTION"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]


instance_group [{ kind: KIND_CPU }]